### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by abdulkadiraktas**
Credits update.

### CODE REVIEW

**Comment by outsider31000** [comment]
This is wrong.
Your tx admin  was private and non found anywhere.  Bytesized made one according to the information on the readme. 
I remember when you made it private   and users complained  cause they could not find it. and then when we uploaded ours you enabled again. I can get the day you did that if you wish.

**Comment by outsider31000** [comment]
I am talking about of when it was uploaded.   Now if it was made before. That i dont know. Only bytesized can answer. But don't make sense  he credit where he got inspired from.

**Comment by abdulkadiraktas** [comment]
Thats true. I removed it because I didn't update the repo. However, when I saw that @AndrewR3K sent very good PR, I opened it again.
After all, it doesn't change the fact that mine is used as the main source.
If you look at the commits https://github.com/VanTheNoble/vorp_txAdminRecipe/commits/main section of the person you are crediting, you can see that it was copied from my repo.

**Comment by outsider31000** [comment]
Allright i will  talk to him if is indeed inspired on yours the credits will be given for certain.  Thanks again. And apologies.

**Comment by outsider31000** [comment]
But yours was private so i have no idea how could it be copied.

**Comment by abdulkadiraktas** [comment]
It wasn't always private. It may have been downloaded when I first posted it.

**Comment by AndrewR3K** [comment]
We have credits at the bottom.

i have only used/looked at the repo listed below when making/updating this codebase.

i have also heavily added fixes and full blown written tutorials.

check readme, we have a section for credit like below.

If this isnt sufficient happy to add your name to the ready credits section as well

Credits and references

_Inspired and derived from: https://github.com/VanTheNoble/vorp_txAdminRecipe
Inspired and derived from: https://forum.cfx.re/t/how-to-setup-a-redm-server/918850
Inspired and derived from: [https://docs.fivem.net/docs/server-manual/setting-up-a-server-txadmi](https://docs.fivem.net/docs/server-manual/setting-up-a-server-txadmin/)

**Comment by AndrewR3K** [comment]
When I made this based the other repo, its was (still is) public, and at the time had 2 years inactivity and was broken. I added some base fixed to a pr to yours which wasnt answered for months (well after this was made). I have also added a lot more and a full blown text tutorial. So thats why The decision was made to make this repo and bring it under our official umbrella.

just to give you context on why this happened.

like I said above tho, we are all about giving credit where credit is due. I had assumed linking your repo would be enough. So happy to add you to our credits section of the readme with some wording about your help/work to get the base of this going.

sorry for this misunderstanding, I definitely appreciate the work you originally put into this ❤️

**Comment by AndrewR3K** [comment]
@abdulkadiraktas @outsider31000 I have gone ahead and created a PR with proper credits to the og repo and writer. https://github.com/VORPCORE/VORP_txAdmin/pull/11

**Comment by abdulkadiraktas** [comment]
While creating this recipe, my goal was to provide a clean base. At that time, I was also interested in creating vorp base script. However, I could not update the repo because I lost interest in the Vorp side due to the attitudes of some people. That's why I closed the repo. As I mentioned I liked that someone added value to the work. And I opened the repo back again. Thanks for the work you do here.
@AndrewR3K

**Comment by Mycroft-Studios** [comment]
All recipes are just a yaml file no? they all use the same functions no? the only recipe u can really steal from or be inspired by is the txadmin example, no?

**Comment by abdulkadiraktas** [comment]
If you build it from scratch yes you are right. However, @AndrewR3K  already forked an existing structure and added it to it, making it this way. So he didn't create it from scratch. That's reason enough to give credit. If you don't know about a topic, please don't comment.

--https://github.com/AndrewR3K/vorp_txAdminRecipe/blob/main/vorp_recipe_qadr.yaml
--description: Bu tarif Vorpcore için abdulkadir aktaş tarafından hazırlanmıştır. (This recipe was prepared for Vorpcore by abdulkadir aktaş + contributers)

**Comment by Mycroft-Studios** [comment]
>If you don't know about a topic, please don't comment.

im well aware of the topic, you might wanna check who i am ;)

**Comment by outsider31000** [comment]
credits were added. thank you all

**Comment by abdulkadiraktas** [comment]
> > If you don't know about a topic, please don't comment.
> 
> im well aware of the topic, you might wanna check who i am ;)

Haha funny kid.
 
@outsider31000 thank you

**Pull request closed without merging**
